version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - sam package--output-template-file packag.yaml --s3-bucket my-bucket
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - packaged.yaml
  cach:
    paths:
      - "node_modules/**/*"
