version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18   
    commands:
      - npm install

  build:
    commands:
      - sam build 
      - sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - packaged.yaml

cache:
  paths:
    - "node_modules/**/*"
