HelloWorldFunction:
  Type: AWS::Serverless::Function
  Properties:
    Handler: app.lambdaHandler
    CodeUri: src/
    Description: A simple Lambda function
    Events:
      ApiEvent:
        Type: Api
        Properties:
          Path: /hello
          Method: GET
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Linear10PercentEvery1Minute
      Alarms:
        - !Ref LambdaErrorAlarm
      Rollback: true

LambdaErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: HelloWorldFunctionErrorAlarm
    MetricName: Errors
    Namespace: AWS/Lambda
    Statistic: Sum
    Period: 60
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: FunctionName
        Value: !Ref HelloWorldFunction
